spring:
  # DB 접속 정보 설정 => localhost:3306
  datasource:
    url: jdbc:mysql://localhost:3306/basiclogin
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect